{"bug_class": "PROVER", "kind": "ERROR", "bug_type": "RESOURCE_LEAK", "qualifier": "resource of type `java.net.Socket` acquired to `clientSocket` by call to `accept()` at line 39 is not released after line 41.", "severity": "HIGH", "visibility": "user", "line": 41, "column": -1, "procedure": "void CoverageReceiverThread.run()", "procedure_id": "org.pitest.mutationtest.CoverageReceiverThread.run():void.5b45e48704e56ec4010387f2bd295a50", "procedure_start_line": 34, "file": "pitest/src/main/java/org/pitest/mutationtest/CoverageReceiverThread.java", "bug_trace": [{"level": 0, "filename": "pitest/src/main/java/org/pitest/mutationtest/CoverageReceiverThread.java", "line_number": 34, "column_number": -1, "description": "start of procedure run()"}, {"level": 0, "filename": "pitest/src/main/java/org/pitest/mutationtest/CoverageReceiverThread.java", "line_number": 36, "column_number": -1, "description": ""}, {"level": 0, "filename": "pitest/src/main/java/org/pitest/mutationtest/CoverageReceiverThread.java", "line_number": 38, "column_number": -1, "description": "Skipping ServerSocket(...): unknown method"}, {"level": 0, "filename": "pitest/src/main/java/org/pitest/mutationtest/CoverageReceiverThread.java", "line_number": 39, "column_number": -1, "description": ""}, {"level": 0, "filename": "pitest/src/main/java/org/pitest/mutationtest/CoverageReceiverThread.java", "line_number": 41, "column_number": -1, "description": ""}], "key": "CoverageReceiverThread.java|run|RESOURCE_LEAK", "node_key": "3451cb93d845d85a147a6855623bf280", "hash": "e5cd0d4fdaafbf68ecbb0630e21199bd", "bug_type_hum": "Resource Leak", "censored_reason": ""}