    @Test
    public static void testApp() throws Exception {

        ParallelThread parallelThread = new ParallelThread();
        List<String> tests = new ArrayList<>();
        //tests.add("HomePageTest1");
        //tests.add("HomePageTest2");
        boolean hasFailures = parallelThread.runner("com.test.site");
        Assert.assertFalse(hasFailures, "Testcases have failed in parallel execution");
    }