{"bug_class": "PROVER", "kind": "ERROR", "bug_type": "NULL_DEREFERENCE", "qualifier": "object returned by `resolve(beanManager,beanClass)` could be null and is dereferenced by call to `getReference(...)` at line 88.", "severity": "HIGH", "visibility": "user", "line": 88, "column": -1, "procedure": "Object Beans.getReference(BeanManager,Class)", "procedure_id": "org.omnifaces.util.Beans.getReference(javax.enterprise.inject.spi.BeanManager,java.lang.Class):java..7b99e0608042f521f06f1730d4b700a3", "procedure_start_line": 88, "file": "src/main/java/org/omnifaces/util/Beans.java", "bug_trace": [{"level": 0, "filename": "src/main/java/org/omnifaces/util/Beans.java", "line_number": 88, "column_number": -1, "description": "start of procedure getReference(...)"}, {"level": 1, "filename": "src/main/java/org/omnifaces/util/Beans.java", "line_number": 69, "column_number": -1, "description": "start of procedure resolve(...)"}, {"level": 1, "filename": "src/main/java/org/omnifaces/util/Beans.java", "line_number": 70, "column_number": -1, "description": "Taking false branch"}, {"level": 1, "filename": "src/main/java/org/omnifaces/util/Beans.java", "line_number": 76, "column_number": -1, "description": "return from a call to Bean Beans.resolve(BeanManager,Class)"}, {"level": 0, "filename": "src/main/java/org/omnifaces/util/Beans.java", "line_number": 88, "column_number": -1, "description": ""}, {"level": 1, "filename": "src/main/java/org/omnifaces/util/Beans.java", "line_number": 101, "column_number": -1, "description": "start of procedure getReference(...)"}], "key": "Beans.java|getReference|NULL_DEREFERENCE", "node_key": "d46e1684de2ca326ba231ad8a5b48143", "hash": "d3ba56359eee6b1dcab8ea83d6c93ade", "bug_type_hum": "Null Dereference", "censored_reason": ""}