{"bug_class": "PROVER", "kind": "ERROR", "bug_type": "NULL_DEREFERENCE", "qualifier": "object returned by `current()` could be null and is dereferenced at line 33.", "severity": "HIGH", "visibility": "user", "line": 33, "column": -1, "procedure": "RemoteInvocation SecureRemoteInvocationFactory.createRemoteInvocation(MethodInvocation)", "procedure_id": "org.jsecurity.spring.remoting.SecureRemoteInvocationFactory.createRemoteInvocation(org.aopalliance.i.58a7cbf9e44a078c13b0d0625ae5b38c", "procedure_start_line": 32, "file": "support/spring/src/org/jsecurity/spring/remoting/SecureRemoteInvocationFactory.java", "bug_trace": [{"level": 0, "filename": "support/spring/src/org/jsecurity/spring/remoting/SecureRemoteInvocationFactory.java", "line_number": 32, "column_number": -1, "description": "start of procedure createRemoteInvocation(...)"}, {"level": 0, "filename": "support/spring/src/org/jsecurity/spring/remoting/SecureRemoteInvocationFactory.java", "line_number": 33, "column_number": -1, "description": ""}, {"level": 1, "filename": "src/org/jsecurity/context/support/ThreadLocalSecurityContext.java", "line_number": 45, "column_number": -1, "description": "start of procedure current()"}, {"level": 1, "filename": "src/org/jsecurity/context/support/ThreadLocalSecurityContext.java", "line_number": 46, "column_number": -1, "description": ""}, {"level": 2, "filename": "src/org/jsecurity/util/ThreadContext.java", "line_number": 96, "column_number": -1, "description": "start of procedure get(...)"}, {"level": 2, "filename": "src/org/jsecurity/util/ThreadContext.java", "line_number": 97, "column_number": -1, "description": "Taking true branch"}, {"level": 2, "filename": "src/org/jsecurity/util/ThreadContext.java", "line_number": 98, "column_number": -1, "description": "Skipping toString(): unknown method"}, {"level": 2, "filename": "src/org/jsecurity/util/ThreadContext.java", "line_number": 99, "column_number": -1, "description": "Skipping trace(...): unknown method"}, {"level": 2, "filename": "src/org/jsecurity/util/ThreadContext.java", "line_number": 101, "column_number": -1, "description": ""}, {"level": 3, "filename": "src/org/jsecurity/util/ThreadContext.java", "line_number": 83, "column_number": -1, "description": "start of procedure getResources()"}, {"level": 3, "filename": "src/org/jsecurity/util/ThreadContext.java", "line_number": 84, "column_number": -1, "description": "return from a call to Map ThreadContext.getResources()"}, {"level": 2, "filename": "src/org/jsecurity/util/ThreadContext.java", "line_number": 101, "column_number": -1, "description": "Skipping get(...): unknown method"}, {"level": 2, "filename": "src/org/jsecurity/util/ThreadContext.java", "line_number": 102, "column_number": -1, "description": "Taking false branch"}, {"level": 2, "filename": "src/org/jsecurity/util/ThreadContext.java", "line_number": 107, "column_number": -1, "description": "return from a call to Object ThreadContext.get(Object)"}, {"level": 1, "filename": "src/org/jsecurity/context/support/ThreadLocalSecurityContext.java", "line_number": 46, "column_number": -1, "description": "return from a call to SecurityContext ThreadLocalSecurityContext.current()"}, {"level": 0, "filename": "support/spring/src/org/jsecurity/spring/remoting/SecureRemoteInvocationFactory.java", "line_number": 33, "column_number": -1, "description": ""}], "key": "SecureRemoteInvocationFactory.java|createRemoteInvocation|NULL_DEREFERENCE", "node_key": "965bbf0a29188a78e25245c992eef045", "hash": "f6f6508589851fc12f4c462f9e12886d", "bug_type_hum": "Null Dereference", "censored_reason": ""}