{"bug_class": "PROVER", "kind": "ERROR", "bug_type": "NULL_DEREFERENCE", "qualifier": "object `result` last assigned on line 284 could be null and is dereferenced at line 290.", "severity": "HIGH", "visibility": "user", "line": 290, "column": -1, "procedure": "void _Test.detect()", "procedure_id": "com.github.underscore._Test.detect():void.a6c93fcfbfe9ca10cbf640e95c08009d", "procedure_start_line": 284, "file": "src/test/java/com/github/underscore/_Test.java", "bug_trace": [{"level": 0, "filename": "src/test/java/com/github/underscore/_Test.java", "line_number": 284, "column_number": -1, "description": "start of procedure detect()"}, {"level": 1, "filename": "src/test/java/com/github/underscore/_Test.java", "line_number": 285, "column_number": -1, "description": "start of procedure _Test$17(...)"}, {"level": 1, "filename": "src/test/java/com/github/underscore/_Test.java", "line_number": 285, "column_number": -1, "description": "return from a call to _Test$17.<init>(_Test)"}, {"level": 0, "filename": "src/test/java/com/github/underscore/_Test.java", "line_number": 284, "column_number": -1, "description": ""}, {"level": 1, "filename": "src/main/java/com/github/underscore/_.java", "line_number": 128, "column_number": -1, "description": "start of procedure detect(...)"}, {"level": 1, "filename": "src/main/java/com/github/underscore/_.java", "line_number": 129, "column_number": -1, "description": ""}, {"level": 2, "filename": "src/main/java/com/github/underscore/_.java", "line_number": 119, "column_number": -1, "description": "start of procedure find(...)"}, {"level": 2, "filename": "src/main/java/com/github/underscore/_.java", "line_number": 120, "column_number": -1, "description": "Taking false branch"}, {"level": 2, "filename": "src/main/java/com/github/underscore/_.java", "line_number": 125, "column_number": -1, "description": "return from a call to Object _.find(Iterable,Predicate)"}, {"level": 1, "filename": "src/main/java/com/github/underscore/_.java", "line_number": 129, "column_number": -1, "description": "return from a call to Object _.detect(Iterable,_Test$17)"}, {"level": 0, "filename": "src/test/java/com/github/underscore/_Test.java", "line_number": 284, "column_number": -1, "description": ""}, {"level": 0, "filename": "src/test/java/com/github/underscore/_Test.java", "line_number": 290, "column_number": -1, "description": ""}], "key": "_Test.java|detect|NULL_DEREFERENCE", "node_key": "15891b12c6ce50257e480adc810587ae", "hash": "5e317cf20e7101025ba66ed62c50bee7", "bug_type_hum": "Null Dereference", "censored_reason": ""}